name: smalltalkCI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        smalltalk: [ Squeak64-trunk, Squeak64-5.3 ]
    name: Test ${{ matrix.smalltalk }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install libpulse
        run: sudo apt install libpulse0
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
      - run: ./scripts/build_version.sh
        if: github.ref == 'refs/heads/master' && matrix.smalltalk == 'Squeak64-5.3'
        shell: bash
        timeout-minutes: 5
      - name: Upload Image
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && matrix.smalltalk == 'Squeak64-5.3'
        with:
          name: sandblocks.zip 
          path: ./deploy/sandblocks.zip
      - name: Upload SAR
        uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master' && matrix.smalltalk == 'Squeak64-5.3'
        with:
          name: sandblocks.sar
          path: ./deploy/sandblocks.sar
